// Generated by gencpp from file text_msgs/bn_pose_srv.msg
// DO NOT EDIT!


#ifndef TEXT_MSGS_MESSAGE_BN_POSE_SRV_H
#define TEXT_MSGS_MESSAGE_BN_POSE_SRV_H

#include <ros/service_traits.h>


#include <text_msgs/bn_pose_srvRequest.h>
#include <text_msgs/bn_pose_srvResponse.h>


namespace text_msgs
{

struct bn_pose_srv
{

typedef bn_pose_srvRequest Request;
typedef bn_pose_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct bn_pose_srv
} // namespace text_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::text_msgs::bn_pose_srv > {
  static const char* value()
  {
    return "a390f42680d4ac2ddfd1904d44d51e95";
  }

  static const char* value(const ::text_msgs::bn_pose_srv&) { return value(); }
};

template<>
struct DataType< ::text_msgs::bn_pose_srv > {
  static const char* value()
  {
    return "text_msgs/bn_pose_srv";
  }

  static const char* value(const ::text_msgs::bn_pose_srv&) { return value(); }
};


// service_traits::MD5Sum< ::text_msgs::bn_pose_srvRequest> should match
// service_traits::MD5Sum< ::text_msgs::bn_pose_srv >
template<>
struct MD5Sum< ::text_msgs::bn_pose_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::text_msgs::bn_pose_srv >::value();
  }
  static const char* value(const ::text_msgs::bn_pose_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::text_msgs::bn_pose_srvRequest> should match
// service_traits::DataType< ::text_msgs::bn_pose_srv >
template<>
struct DataType< ::text_msgs::bn_pose_srvRequest>
{
  static const char* value()
  {
    return DataType< ::text_msgs::bn_pose_srv >::value();
  }
  static const char* value(const ::text_msgs::bn_pose_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::text_msgs::bn_pose_srvResponse> should match
// service_traits::MD5Sum< ::text_msgs::bn_pose_srv >
template<>
struct MD5Sum< ::text_msgs::bn_pose_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::text_msgs::bn_pose_srv >::value();
  }
  static const char* value(const ::text_msgs::bn_pose_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::text_msgs::bn_pose_srvResponse> should match
// service_traits::DataType< ::text_msgs::bn_pose_srv >
template<>
struct DataType< ::text_msgs::bn_pose_srvResponse>
{
  static const char* value()
  {
    return DataType< ::text_msgs::bn_pose_srv >::value();
  }
  static const char* value(const ::text_msgs::bn_pose_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEXT_MSGS_MESSAGE_BN_POSE_SRV_H
