// Generated by gencpp from file text_msgs/int_arr.msg
// DO NOT EDIT!


#ifndef TEXT_MSGS_MESSAGE_INT_ARR_H
#define TEXT_MSGS_MESSAGE_INT_ARR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace text_msgs
{
template <class ContainerAllocator>
struct int_arr_
{
  typedef int_arr_<ContainerAllocator> Type;

  int_arr_()
    : point()  {
    }
  int_arr_(const ContainerAllocator& _alloc)
    : point(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _point_type;
  _point_type point;





  typedef boost::shared_ptr< ::text_msgs::int_arr_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::text_msgs::int_arr_<ContainerAllocator> const> ConstPtr;

}; // struct int_arr_

typedef ::text_msgs::int_arr_<std::allocator<void> > int_arr;

typedef boost::shared_ptr< ::text_msgs::int_arr > int_arrPtr;
typedef boost::shared_ptr< ::text_msgs::int_arr const> int_arrConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::text_msgs::int_arr_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::text_msgs::int_arr_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::text_msgs::int_arr_<ContainerAllocator1> & lhs, const ::text_msgs::int_arr_<ContainerAllocator2> & rhs)
{
  return lhs.point == rhs.point;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::text_msgs::int_arr_<ContainerAllocator1> & lhs, const ::text_msgs::int_arr_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace text_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::text_msgs::int_arr_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::text_msgs::int_arr_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::text_msgs::int_arr_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::text_msgs::int_arr_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::text_msgs::int_arr_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::text_msgs::int_arr_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::text_msgs::int_arr_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9d43aa930d9591879a0c30e6abefcb2e";
  }

  static const char* value(const ::text_msgs::int_arr_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9d43aa930d959187ULL;
  static const uint64_t static_value2 = 0x9a0c30e6abefcb2eULL;
};

template<class ContainerAllocator>
struct DataType< ::text_msgs::int_arr_<ContainerAllocator> >
{
  static const char* value()
  {
    return "text_msgs/int_arr";
  }

  static const char* value(const ::text_msgs::int_arr_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::text_msgs::int_arr_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] point\n"
;
  }

  static const char* value(const ::text_msgs::int_arr_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::text_msgs::int_arr_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.point);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct int_arr_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::text_msgs::int_arr_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::text_msgs::int_arr_<ContainerAllocator>& v)
  {
    s << indent << "point[]" << std::endl;
    for (size_t i = 0; i < v.point.size(); ++i)
    {
      s << indent << "  point[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.point[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEXT_MSGS_MESSAGE_INT_ARR_H
