// Generated by gencpp from file text_msgs/manipulationResponse.msg
// DO NOT EDIT!


#ifndef TEXT_MSGS_MESSAGE_MANIPULATIONRESPONSE_H
#define TEXT_MSGS_MESSAGE_MANIPULATIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace text_msgs
{
template <class ContainerAllocator>
struct manipulationResponse_
{
  typedef manipulationResponse_<ContainerAllocator> Type;

  manipulationResponse_()
    : state()  {
    }
  manipulationResponse_(const ContainerAllocator& _alloc)
    : state(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::text_msgs::manipulationResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::text_msgs::manipulationResponse_<ContainerAllocator> const> ConstPtr;

}; // struct manipulationResponse_

typedef ::text_msgs::manipulationResponse_<std::allocator<void> > manipulationResponse;

typedef boost::shared_ptr< ::text_msgs::manipulationResponse > manipulationResponsePtr;
typedef boost::shared_ptr< ::text_msgs::manipulationResponse const> manipulationResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::text_msgs::manipulationResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::text_msgs::manipulationResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::text_msgs::manipulationResponse_<ContainerAllocator1> & lhs, const ::text_msgs::manipulationResponse_<ContainerAllocator2> & rhs)
{
  return lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::text_msgs::manipulationResponse_<ContainerAllocator1> & lhs, const ::text_msgs::manipulationResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace text_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::text_msgs::manipulationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::text_msgs::manipulationResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::text_msgs::manipulationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::text_msgs::manipulationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::text_msgs::manipulationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::text_msgs::manipulationResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::text_msgs::manipulationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "af6d3a99f0fbeb66d3248fa4b3e675fb";
  }

  static const char* value(const ::text_msgs::manipulationResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaf6d3a99f0fbeb66ULL;
  static const uint64_t static_value2 = 0xd3248fa4b3e675fbULL;
};

template<class ContainerAllocator>
struct DataType< ::text_msgs::manipulationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "text_msgs/manipulationResponse";
  }

  static const char* value(const ::text_msgs::manipulationResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::text_msgs::manipulationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#Response data\n"
"string state \n"
"\n"
;
  }

  static const char* value(const ::text_msgs::manipulationResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::text_msgs::manipulationResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct manipulationResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::text_msgs::manipulationResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::text_msgs::manipulationResponse_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEXT_MSGS_MESSAGE_MANIPULATIONRESPONSE_H
