// Generated by gencpp from file text_msgs/manipulationRequest.msg
// DO NOT EDIT!


#ifndef TEXT_MSGS_MESSAGE_MANIPULATIONREQUEST_H
#define TEXT_MSGS_MESSAGE_MANIPULATIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace text_msgs
{
template <class ContainerAllocator>
struct manipulationRequest_
{
  typedef manipulationRequest_<ContainerAllocator> Type;

  manipulationRequest_()
    : mode()
    , object()
    , pose()  {
    }
  manipulationRequest_(const ContainerAllocator& _alloc)
    : mode(_alloc)
    , object(_alloc)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _mode_type;
  _mode_type mode;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _object_type;
  _object_type object;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::text_msgs::manipulationRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::text_msgs::manipulationRequest_<ContainerAllocator> const> ConstPtr;

}; // struct manipulationRequest_

typedef ::text_msgs::manipulationRequest_<std::allocator<void> > manipulationRequest;

typedef boost::shared_ptr< ::text_msgs::manipulationRequest > manipulationRequestPtr;
typedef boost::shared_ptr< ::text_msgs::manipulationRequest const> manipulationRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::text_msgs::manipulationRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::text_msgs::manipulationRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::text_msgs::manipulationRequest_<ContainerAllocator1> & lhs, const ::text_msgs::manipulationRequest_<ContainerAllocator2> & rhs)
{
  return lhs.mode == rhs.mode &&
    lhs.object == rhs.object &&
    lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::text_msgs::manipulationRequest_<ContainerAllocator1> & lhs, const ::text_msgs::manipulationRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace text_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::text_msgs::manipulationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::text_msgs::manipulationRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::text_msgs::manipulationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::text_msgs::manipulationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::text_msgs::manipulationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::text_msgs::manipulationRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::text_msgs::manipulationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "386579ff94d62e7c2cce2810ddb954c2";
  }

  static const char* value(const ::text_msgs::manipulationRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x386579ff94d62e7cULL;
  static const uint64_t static_value2 = 0x2cce2810ddb954c2ULL;
};

template<class ContainerAllocator>
struct DataType< ::text_msgs::manipulationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "text_msgs/manipulationRequest";
  }

  static const char* value(const ::text_msgs::manipulationRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::text_msgs::manipulationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#Request data\n"
"string mode\n"
"string object\n"
"geometry_msgs/Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::text_msgs::manipulationRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::text_msgs::manipulationRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
      stream.next(m.object);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct manipulationRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::text_msgs::manipulationRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::text_msgs::manipulationRequest_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.mode);
    s << indent << "object: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.object);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEXT_MSGS_MESSAGE_MANIPULATIONREQUEST_H
