// Generated by gencpp from file text_msgs/manipulation.msg
// DO NOT EDIT!


#ifndef TEXT_MSGS_MESSAGE_MANIPULATION_H
#define TEXT_MSGS_MESSAGE_MANIPULATION_H

#include <ros/service_traits.h>


#include <text_msgs/manipulationRequest.h>
#include <text_msgs/manipulationResponse.h>


namespace text_msgs
{

struct manipulation
{

typedef manipulationRequest Request;
typedef manipulationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct manipulation
} // namespace text_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::text_msgs::manipulation > {
  static const char* value()
  {
    return "940776247decf73dc39a0d8aa126a552";
  }

  static const char* value(const ::text_msgs::manipulation&) { return value(); }
};

template<>
struct DataType< ::text_msgs::manipulation > {
  static const char* value()
  {
    return "text_msgs/manipulation";
  }

  static const char* value(const ::text_msgs::manipulation&) { return value(); }
};


// service_traits::MD5Sum< ::text_msgs::manipulationRequest> should match
// service_traits::MD5Sum< ::text_msgs::manipulation >
template<>
struct MD5Sum< ::text_msgs::manipulationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::text_msgs::manipulation >::value();
  }
  static const char* value(const ::text_msgs::manipulationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::text_msgs::manipulationRequest> should match
// service_traits::DataType< ::text_msgs::manipulation >
template<>
struct DataType< ::text_msgs::manipulationRequest>
{
  static const char* value()
  {
    return DataType< ::text_msgs::manipulation >::value();
  }
  static const char* value(const ::text_msgs::manipulationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::text_msgs::manipulationResponse> should match
// service_traits::MD5Sum< ::text_msgs::manipulation >
template<>
struct MD5Sum< ::text_msgs::manipulationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::text_msgs::manipulation >::value();
  }
  static const char* value(const ::text_msgs::manipulationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::text_msgs::manipulationResponse> should match
// service_traits::DataType< ::text_msgs::manipulation >
template<>
struct DataType< ::text_msgs::manipulationResponse>
{
  static const char* value()
  {
    return DataType< ::text_msgs::manipulation >::value();
  }
  static const char* value(const ::text_msgs::manipulationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEXT_MSGS_MESSAGE_MANIPULATION_H
