// Generated by gencpp from file text_msgs/object_only.msg
// DO NOT EDIT!


#ifndef TEXT_MSGS_MESSAGE_OBJECT_ONLY_H
#define TEXT_MSGS_MESSAGE_OBJECT_ONLY_H

#include <ros/service_traits.h>


#include <text_msgs/object_onlyRequest.h>
#include <text_msgs/object_onlyResponse.h>


namespace text_msgs
{

struct object_only
{

typedef object_onlyRequest Request;
typedef object_onlyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct object_only
} // namespace text_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::text_msgs::object_only > {
  static const char* value()
  {
    return "1af0bf5105da2ef053fba4cb2b4821cc";
  }

  static const char* value(const ::text_msgs::object_only&) { return value(); }
};

template<>
struct DataType< ::text_msgs::object_only > {
  static const char* value()
  {
    return "text_msgs/object_only";
  }

  static const char* value(const ::text_msgs::object_only&) { return value(); }
};


// service_traits::MD5Sum< ::text_msgs::object_onlyRequest> should match
// service_traits::MD5Sum< ::text_msgs::object_only >
template<>
struct MD5Sum< ::text_msgs::object_onlyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::text_msgs::object_only >::value();
  }
  static const char* value(const ::text_msgs::object_onlyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::text_msgs::object_onlyRequest> should match
// service_traits::DataType< ::text_msgs::object_only >
template<>
struct DataType< ::text_msgs::object_onlyRequest>
{
  static const char* value()
  {
    return DataType< ::text_msgs::object_only >::value();
  }
  static const char* value(const ::text_msgs::object_onlyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::text_msgs::object_onlyResponse> should match
// service_traits::MD5Sum< ::text_msgs::object_only >
template<>
struct MD5Sum< ::text_msgs::object_onlyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::text_msgs::object_only >::value();
  }
  static const char* value(const ::text_msgs::object_onlyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::text_msgs::object_onlyResponse> should match
// service_traits::DataType< ::text_msgs::object_only >
template<>
struct DataType< ::text_msgs::object_onlyResponse>
{
  static const char* value()
  {
    return DataType< ::text_msgs::object_only >::value();
  }
  static const char* value(const ::text_msgs::object_onlyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEXT_MSGS_MESSAGE_OBJECT_ONLY_H
