// Generated by gencpp from file text_msgs/pose_state.msg
// DO NOT EDIT!


#ifndef TEXT_MSGS_MESSAGE_POSE_STATE_H
#define TEXT_MSGS_MESSAGE_POSE_STATE_H

#include <ros/service_traits.h>


#include <text_msgs/pose_stateRequest.h>
#include <text_msgs/pose_stateResponse.h>


namespace text_msgs
{

struct pose_state
{

typedef pose_stateRequest Request;
typedef pose_stateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct pose_state
} // namespace text_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::text_msgs::pose_state > {
  static const char* value()
  {
    return "e25f37c302ffcec97c8207b6fff18d73";
  }

  static const char* value(const ::text_msgs::pose_state&) { return value(); }
};

template<>
struct DataType< ::text_msgs::pose_state > {
  static const char* value()
  {
    return "text_msgs/pose_state";
  }

  static const char* value(const ::text_msgs::pose_state&) { return value(); }
};


// service_traits::MD5Sum< ::text_msgs::pose_stateRequest> should match
// service_traits::MD5Sum< ::text_msgs::pose_state >
template<>
struct MD5Sum< ::text_msgs::pose_stateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::text_msgs::pose_state >::value();
  }
  static const char* value(const ::text_msgs::pose_stateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::text_msgs::pose_stateRequest> should match
// service_traits::DataType< ::text_msgs::pose_state >
template<>
struct DataType< ::text_msgs::pose_stateRequest>
{
  static const char* value()
  {
    return DataType< ::text_msgs::pose_state >::value();
  }
  static const char* value(const ::text_msgs::pose_stateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::text_msgs::pose_stateResponse> should match
// service_traits::MD5Sum< ::text_msgs::pose_state >
template<>
struct MD5Sum< ::text_msgs::pose_stateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::text_msgs::pose_state >::value();
  }
  static const char* value(const ::text_msgs::pose_stateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::text_msgs::pose_stateResponse> should match
// service_traits::DataType< ::text_msgs::pose_state >
template<>
struct DataType< ::text_msgs::pose_stateResponse>
{
  static const char* value()
  {
    return DataType< ::text_msgs::pose_state >::value();
  }
  static const char* value(const ::text_msgs::pose_stateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEXT_MSGS_MESSAGE_POSE_STATE_H
