// Generated by gencpp from file text_msgs/predict_switchRequest.msg
// DO NOT EDIT!


#ifndef TEXT_MSGS_MESSAGE_PREDICT_SWITCHREQUEST_H
#define TEXT_MSGS_MESSAGE_PREDICT_SWITCHREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace text_msgs
{
template <class ContainerAllocator>
struct predict_switchRequest_
{
  typedef predict_switchRequest_<ContainerAllocator> Type;

  predict_switchRequest_()
    : data(false)  {
    }
  predict_switchRequest_(const ContainerAllocator& _alloc)
    : data(false)  {
  (void)_alloc;
    }



   typedef uint8_t _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::text_msgs::predict_switchRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::text_msgs::predict_switchRequest_<ContainerAllocator> const> ConstPtr;

}; // struct predict_switchRequest_

typedef ::text_msgs::predict_switchRequest_<std::allocator<void> > predict_switchRequest;

typedef boost::shared_ptr< ::text_msgs::predict_switchRequest > predict_switchRequestPtr;
typedef boost::shared_ptr< ::text_msgs::predict_switchRequest const> predict_switchRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::text_msgs::predict_switchRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::text_msgs::predict_switchRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::text_msgs::predict_switchRequest_<ContainerAllocator1> & lhs, const ::text_msgs::predict_switchRequest_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::text_msgs::predict_switchRequest_<ContainerAllocator1> & lhs, const ::text_msgs::predict_switchRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace text_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::text_msgs::predict_switchRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::text_msgs::predict_switchRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::text_msgs::predict_switchRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::text_msgs::predict_switchRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::text_msgs::predict_switchRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::text_msgs::predict_switchRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::text_msgs::predict_switchRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8b94c1b53db61fb6aed406028ad6332a";
  }

  static const char* value(const ::text_msgs::predict_switchRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8b94c1b53db61fb6ULL;
  static const uint64_t static_value2 = 0xaed406028ad6332aULL;
};

template<class ContainerAllocator>
struct DataType< ::text_msgs::predict_switchRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "text_msgs/predict_switchRequest";
  }

  static const char* value(const ::text_msgs::predict_switchRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::text_msgs::predict_switchRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#Request data\n"
"bool data # for switch status\n"
;
  }

  static const char* value(const ::text_msgs::predict_switchRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::text_msgs::predict_switchRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct predict_switchRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::text_msgs::predict_switchRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::text_msgs::predict_switchRequest_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEXT_MSGS_MESSAGE_PREDICT_SWITCHREQUEST_H
