// Generated by gencpp from file text_msgs/predict_switch.msg
// DO NOT EDIT!


#ifndef TEXT_MSGS_MESSAGE_PREDICT_SWITCH_H
#define TEXT_MSGS_MESSAGE_PREDICT_SWITCH_H

#include <ros/service_traits.h>


#include <text_msgs/predict_switchRequest.h>
#include <text_msgs/predict_switchResponse.h>


namespace text_msgs
{

struct predict_switch
{

typedef predict_switchRequest Request;
typedef predict_switchResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct predict_switch
} // namespace text_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::text_msgs::predict_switch > {
  static const char* value()
  {
    return "b39707c144dc811845d1401dd6f773fb";
  }

  static const char* value(const ::text_msgs::predict_switch&) { return value(); }
};

template<>
struct DataType< ::text_msgs::predict_switch > {
  static const char* value()
  {
    return "text_msgs/predict_switch";
  }

  static const char* value(const ::text_msgs::predict_switch&) { return value(); }
};


// service_traits::MD5Sum< ::text_msgs::predict_switchRequest> should match
// service_traits::MD5Sum< ::text_msgs::predict_switch >
template<>
struct MD5Sum< ::text_msgs::predict_switchRequest>
{
  static const char* value()
  {
    return MD5Sum< ::text_msgs::predict_switch >::value();
  }
  static const char* value(const ::text_msgs::predict_switchRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::text_msgs::predict_switchRequest> should match
// service_traits::DataType< ::text_msgs::predict_switch >
template<>
struct DataType< ::text_msgs::predict_switchRequest>
{
  static const char* value()
  {
    return DataType< ::text_msgs::predict_switch >::value();
  }
  static const char* value(const ::text_msgs::predict_switchRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::text_msgs::predict_switchResponse> should match
// service_traits::MD5Sum< ::text_msgs::predict_switch >
template<>
struct MD5Sum< ::text_msgs::predict_switchResponse>
{
  static const char* value()
  {
    return MD5Sum< ::text_msgs::predict_switch >::value();
  }
  static const char* value(const ::text_msgs::predict_switchResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::text_msgs::predict_switchResponse> should match
// service_traits::DataType< ::text_msgs::predict_switch >
template<>
struct DataType< ::text_msgs::predict_switchResponse>
{
  static const char* value()
  {
    return DataType< ::text_msgs::predict_switch >::value();
  }
  static const char* value(const ::text_msgs::predict_switchResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEXT_MSGS_MESSAGE_PREDICT_SWITCH_H
