// Generated by gencpp from file text_msgs/predict_switchResponse.msg
// DO NOT EDIT!


#ifndef TEXT_MSGS_MESSAGE_PREDICT_SWITCHRESPONSE_H
#define TEXT_MSGS_MESSAGE_PREDICT_SWITCHRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace text_msgs
{
template <class ContainerAllocator>
struct predict_switchResponse_
{
  typedef predict_switchResponse_<ContainerAllocator> Type;

  predict_switchResponse_()
    : result()  {
    }
  predict_switchResponse_(const ContainerAllocator& _alloc)
    : result(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::text_msgs::predict_switchResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::text_msgs::predict_switchResponse_<ContainerAllocator> const> ConstPtr;

}; // struct predict_switchResponse_

typedef ::text_msgs::predict_switchResponse_<std::allocator<void> > predict_switchResponse;

typedef boost::shared_ptr< ::text_msgs::predict_switchResponse > predict_switchResponsePtr;
typedef boost::shared_ptr< ::text_msgs::predict_switchResponse const> predict_switchResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::text_msgs::predict_switchResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::text_msgs::predict_switchResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::text_msgs::predict_switchResponse_<ContainerAllocator1> & lhs, const ::text_msgs::predict_switchResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::text_msgs::predict_switchResponse_<ContainerAllocator1> & lhs, const ::text_msgs::predict_switchResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace text_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::text_msgs::predict_switchResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::text_msgs::predict_switchResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::text_msgs::predict_switchResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::text_msgs::predict_switchResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::text_msgs::predict_switchResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::text_msgs::predict_switchResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::text_msgs::predict_switchResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c22f2a1ed8654a0b365f1bb3f7ff2c0f";
  }

  static const char* value(const ::text_msgs::predict_switchResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc22f2a1ed8654a0bULL;
  static const uint64_t static_value2 = 0x365f1bb3f7ff2c0fULL;
};

template<class ContainerAllocator>
struct DataType< ::text_msgs::predict_switchResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "text_msgs/predict_switchResponse";
  }

  static const char* value(const ::text_msgs::predict_switchResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::text_msgs::predict_switchResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#Response data\n"
"string result # for mission result\n"
;
  }

  static const char* value(const ::text_msgs::predict_switchResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::text_msgs::predict_switchResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct predict_switchResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::text_msgs::predict_switchResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::text_msgs::predict_switchResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEXT_MSGS_MESSAGE_PREDICT_SWITCHRESPONSE_H
