// Generated by gencpp from file text_msgs/text_recognize_srv.msg
// DO NOT EDIT!


#ifndef TEXT_MSGS_MESSAGE_TEXT_RECOGNIZE_SRV_H
#define TEXT_MSGS_MESSAGE_TEXT_RECOGNIZE_SRV_H

#include <ros/service_traits.h>


#include <text_msgs/text_recognize_srvRequest.h>
#include <text_msgs/text_recognize_srvResponse.h>


namespace text_msgs
{

struct text_recognize_srv
{

typedef text_recognize_srvRequest Request;
typedef text_recognize_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct text_recognize_srv
} // namespace text_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::text_msgs::text_recognize_srv > {
  static const char* value()
  {
    return "6a29ed0e96899d05731bd1631ebb881a";
  }

  static const char* value(const ::text_msgs::text_recognize_srv&) { return value(); }
};

template<>
struct DataType< ::text_msgs::text_recognize_srv > {
  static const char* value()
  {
    return "text_msgs/text_recognize_srv";
  }

  static const char* value(const ::text_msgs::text_recognize_srv&) { return value(); }
};


// service_traits::MD5Sum< ::text_msgs::text_recognize_srvRequest> should match
// service_traits::MD5Sum< ::text_msgs::text_recognize_srv >
template<>
struct MD5Sum< ::text_msgs::text_recognize_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::text_msgs::text_recognize_srv >::value();
  }
  static const char* value(const ::text_msgs::text_recognize_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::text_msgs::text_recognize_srvRequest> should match
// service_traits::DataType< ::text_msgs::text_recognize_srv >
template<>
struct DataType< ::text_msgs::text_recognize_srvRequest>
{
  static const char* value()
  {
    return DataType< ::text_msgs::text_recognize_srv >::value();
  }
  static const char* value(const ::text_msgs::text_recognize_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::text_msgs::text_recognize_srvResponse> should match
// service_traits::MD5Sum< ::text_msgs::text_recognize_srv >
template<>
struct MD5Sum< ::text_msgs::text_recognize_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::text_msgs::text_recognize_srv >::value();
  }
  static const char* value(const ::text_msgs::text_recognize_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::text_msgs::text_recognize_srvResponse> should match
// service_traits::DataType< ::text_msgs::text_recognize_srv >
template<>
struct DataType< ::text_msgs::text_recognize_srvResponse>
{
  static const char* value()
  {
    return DataType< ::text_msgs::text_recognize_srv >::value();
  }
  static const char* value(const ::text_msgs::text_recognize_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEXT_MSGS_MESSAGE_TEXT_RECOGNIZE_SRV_H
