// Generated by gencpp from file text_msgs/text_detection_srv.msg
// DO NOT EDIT!


#ifndef TEXT_MSGS_MESSAGE_TEXT_DETECTION_SRV_H
#define TEXT_MSGS_MESSAGE_TEXT_DETECTION_SRV_H

#include <ros/service_traits.h>


#include <text_msgs/text_detection_srvRequest.h>
#include <text_msgs/text_detection_srvResponse.h>


namespace text_msgs
{

struct text_detection_srv
{

typedef text_detection_srvRequest Request;
typedef text_detection_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct text_detection_srv
} // namespace text_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::text_msgs::text_detection_srv > {
  static const char* value()
  {
    return "cd159a3525dc687ad17b1858d3f91e0f";
  }

  static const char* value(const ::text_msgs::text_detection_srv&) { return value(); }
};

template<>
struct DataType< ::text_msgs::text_detection_srv > {
  static const char* value()
  {
    return "text_msgs/text_detection_srv";
  }

  static const char* value(const ::text_msgs::text_detection_srv&) { return value(); }
};


// service_traits::MD5Sum< ::text_msgs::text_detection_srvRequest> should match
// service_traits::MD5Sum< ::text_msgs::text_detection_srv >
template<>
struct MD5Sum< ::text_msgs::text_detection_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::text_msgs::text_detection_srv >::value();
  }
  static const char* value(const ::text_msgs::text_detection_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::text_msgs::text_detection_srvRequest> should match
// service_traits::DataType< ::text_msgs::text_detection_srv >
template<>
struct DataType< ::text_msgs::text_detection_srvRequest>
{
  static const char* value()
  {
    return DataType< ::text_msgs::text_detection_srv >::value();
  }
  static const char* value(const ::text_msgs::text_detection_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::text_msgs::text_detection_srvResponse> should match
// service_traits::MD5Sum< ::text_msgs::text_detection_srv >
template<>
struct MD5Sum< ::text_msgs::text_detection_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::text_msgs::text_detection_srv >::value();
  }
  static const char* value(const ::text_msgs::text_detection_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::text_msgs::text_detection_srvResponse> should match
// service_traits::DataType< ::text_msgs::text_detection_srv >
template<>
struct DataType< ::text_msgs::text_detection_srvResponse>
{
  static const char* value()
  {
    return DataType< ::text_msgs::text_detection_srv >::value();
  }
  static const char* value(const ::text_msgs::text_detection_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEXT_MSGS_MESSAGE_TEXT_DETECTION_SRV_H
