// Generated by gencpp from file text_msgs/text_recognize_srvRequest.msg
// DO NOT EDIT!


#ifndef TEXT_MSGS_MESSAGE_TEXT_RECOGNIZE_SRVREQUEST_H
#define TEXT_MSGS_MESSAGE_TEXT_RECOGNIZE_SRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <text_msgs/text_detection_array.h>

namespace text_msgs
{
template <class ContainerAllocator>
struct text_recognize_srvRequest_
{
  typedef text_recognize_srvRequest_<ContainerAllocator> Type;

  text_recognize_srvRequest_()
    : direct(0)
    , data()  {
    }
  text_recognize_srvRequest_(const ContainerAllocator& _alloc)
    : direct(0)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _direct_type;
  _direct_type direct;

   typedef  ::text_msgs::text_detection_array_<ContainerAllocator>  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::text_msgs::text_recognize_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::text_msgs::text_recognize_srvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct text_recognize_srvRequest_

typedef ::text_msgs::text_recognize_srvRequest_<std::allocator<void> > text_recognize_srvRequest;

typedef boost::shared_ptr< ::text_msgs::text_recognize_srvRequest > text_recognize_srvRequestPtr;
typedef boost::shared_ptr< ::text_msgs::text_recognize_srvRequest const> text_recognize_srvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::text_msgs::text_recognize_srvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::text_msgs::text_recognize_srvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::text_msgs::text_recognize_srvRequest_<ContainerAllocator1> & lhs, const ::text_msgs::text_recognize_srvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.direct == rhs.direct &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::text_msgs::text_recognize_srvRequest_<ContainerAllocator1> & lhs, const ::text_msgs::text_recognize_srvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace text_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::text_msgs::text_recognize_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::text_msgs::text_recognize_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::text_msgs::text_recognize_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::text_msgs::text_recognize_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::text_msgs::text_recognize_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::text_msgs::text_recognize_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::text_msgs::text_recognize_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6b4af87a7bc8bef2fd028106b18e5053";
  }

  static const char* value(const ::text_msgs::text_recognize_srvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6b4af87a7bc8bef2ULL;
  static const uint64_t static_value2 = 0xfd028106b18e5053ULL;
};

template<class ContainerAllocator>
struct DataType< ::text_msgs::text_recognize_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "text_msgs/text_recognize_srvRequest";
  }

  static const char* value(const ::text_msgs::text_recognize_srvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::text_msgs::text_recognize_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#Request data\n"
"int32 direct   # 0 = 0, 1 = 90, 2 = 180, 3 = 270\n"
"text_detection_array data\n"
"\n"
"================================================================================\n"
"MSG: text_msgs/text_detection_array\n"
"string status				# O for non_return , X for return \n"
"sensor_msgs/Image image\n"
"sensor_msgs/Image depth\n"
"int32 bb_count\n"
"text_detection_msg[] text_array\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: text_msgs/text_detection_msg\n"
"string status				# O for non_return , X for return \n"
"float64 probability\n"
"geometry_msgs/Pose pose\n"
"bb_box box\n"
"int_arr[] contour\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: text_msgs/bb_box\n"
"int32 xmax\n"
"int32 xmin\n"
"int32 ymax\n"
"int32 ymin\n"
"================================================================================\n"
"MSG: text_msgs/int_arr\n"
"int32[] point\n"
;
  }

  static const char* value(const ::text_msgs::text_recognize_srvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::text_msgs::text_recognize_srvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.direct);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct text_recognize_srvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::text_msgs::text_recognize_srvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::text_msgs::text_recognize_srvRequest_<ContainerAllocator>& v)
  {
    s << indent << "direct: ";
    Printer<int32_t>::stream(s, indent + "  ", v.direct);
    s << indent << "data: ";
    s << std::endl;
    Printer< ::text_msgs::text_detection_array_<ContainerAllocator> >::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEXT_MSGS_MESSAGE_TEXT_RECOGNIZE_SRVREQUEST_H
